apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers: 
      - name: postgres
        image: postgres:latest
        ports:
          - containerPort: 5433
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user

          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:  
                name: postgres-secret
                key: postgres-port

          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: postgres-secret
                key: postgres-password

          - name: POSTGRES_DB
            valueFrom: 
              secretKeyRef: 
                name: postgres-secret
                key: postgres-db
---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5433
      nodePort: 30101
